name: Build and deploy
on:
  push:
    branches:
      - master
      - feature/**
    tags:
      - v*.*.*

jobs:
  build:
    uses: dreaded_x/workflows/.gitea/workflows/rust-kubernetes.yaml@f948dd0b510b112852c22b8cecd5fd7a3fb35027
    secrets: inherit
